version: "3.4"

services:
  agent:
    environment:
      - PYTHON_VENV_DIR=${PYTHON_VENV_DIR}
      - APP_DIR=${APP_DIR}
      - LOG_DIR=${LOG_DIR}
      - CONF_DIR=${CONF_DIR}
      - JSON_SCHEMA_DIR=${JSON_SCHEMA_DIR}
      - TEMP_DIR=${TEMP_DIR}
      - SCRIPTS_DIR=${SCRIPTS_DIR}
      - LOG_LEVEL=${LOG_LEVEL}
    build:
      context: .
      args:
        - BASE_DIR=${BASE_DIR}
        - PYTHON_VENV_DIR=${PYTHON_VENV_DIR}
        - APP_DIR=${APP_DIR}
        - APP_USER=${APP_USER}
        - LOG_DIR=${LOG_DIR}
        - TEMP_DIR=${TEMP_DIR}
        - SCRIPTS_DIR=${SCRIPTS_DIR}
    network_mode: host
